from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_formAgregar(object):
    def setupUi(self, formAgregar):
        formAgregar.setObjectName("formAgregar")
        formAgregar.resize(415, 328)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(formAgregar)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=formAgregar)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.txtAEmpleado = QtWidgets.QLineEdit(parent=formAgregar)
        self.txtAEmpleado.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.UpArrowCursor))
        self.txtAEmpleado.setObjectName("txtAEmpleado")
        self.horizontalLayout.addWidget(self.txtAEmpleado)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=formAgregar)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.txtANomComp = QtWidgets.QLineEdit(parent=formAgregar)
        self.txtANomComp.setObjectName("txtANomComp")
        self.horizontalLayout_2.addWidget(self.txtANomComp)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(parent=formAgregar)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.txtANumCentro = QtWidgets.QLineEdit(parent=formAgregar)
        self.txtANumCentro.setObjectName("txtANumCentro")
        self.horizontalLayout_3.addWidget(self.txtANumCentro)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(parent=formAgregar)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.dateAfecha = QtWidgets.QDateEdit(parent=formAgregar)
        self.dateAfecha.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateAfecha.setObjectName("dateAfecha")
        self.horizontalLayout_4.addWidget(self.dateAfecha)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(parent=formAgregar)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.boxAPuesto = QtWidgets.QComboBox(parent=formAgregar)
        self.boxAPuesto.setObjectName("boxAPuesto")
        self.boxAPuesto.addItem("")
        self.boxAPuesto.addItem("")
        self.boxAPuesto.addItem("")
        self.boxAPuesto.addItem("")
        self.boxAPuesto.addItem("")
        self.horizontalLayout_5.addWidget(self.boxAPuesto)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(parent=formAgregar)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.txtASalario = QtWidgets.QLineEdit(parent=formAgregar)
        self.txtASalario.setObjectName("txtASalario")
        self.horizontalLayout_6.addWidget(self.txtASalario)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(parent=formAgregar)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.boxAGerente = QtWidgets.QComboBox(parent=formAgregar)
        self.boxAGerente.setObjectName("boxAGerente")
        self.horizontalLayout_7.addWidget(self.boxAGerente)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.brnAEditar = QtWidgets.QPushButton(parent=formAgregar)
        self.brnAEditar.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.brnAEditar.setFont(font)
        self.brnAEditar.setObjectName("brnAEditar")
        self.verticalLayout_2.addWidget(self.brnAEditar)
        self.brnARegresar = QtWidgets.QPushButton(parent=formAgregar)
        self.brnARegresar.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.brnARegresar.setFont(font)
        self.brnARegresar.setObjectName("brnARegresar")
        self.verticalLayout_2.addWidget(self.brnARegresar)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)

        self.retranslateUi(formAgregar)
        QtCore.QMetaObject.connectSlotsByName(formAgregar)

    def retranslateUi(self, formAgregar):
        _translate = QtCore.QCoreApplication.translate
        formAgregar.setWindowTitle(_translate("formAgregar", "Agregar"))
        self.label.setText(_translate("formAgregar", "# Empleado"))
        self.label_2.setText(_translate("formAgregar", "Nombre completo"))
        self.label_6.setText(_translate("formAgregar", "# Centro"))
        self.label_5.setText(_translate("formAgregar", "Fecha ingreso"))
        self.label_4.setText(_translate("formAgregar", "Puesto Actual"))
        self.boxAPuesto.setItemText(0, _translate("formAgregar", "Gerente"))
        self.boxAPuesto.setItemText(1, _translate("formAgregar", "Lider de Proyecto"))
        self.boxAPuesto.setItemText(2, _translate("formAgregar", "Desarrollador"))
        self.boxAPuesto.setItemText(3, _translate("formAgregar", "Tester"))
        self.boxAPuesto.setItemText(4, _translate("formAgregar", "Analista"))
        self.label_3.setText(_translate("formAgregar", "Salario"))
        self.label_7.setText(_translate("formAgregar", "Gerente"))
        self.brnAEditar.setText(_translate("formAgregar", "Editar datos"))
        self.brnARegresar.setText(_translate("formAgregar", "Regresar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formAgregar = QtWidgets.QWidget()
    ui = Ui_formAgregar()
    ui.setupUi(formAgregar)
    formAgregar.show()
    sys.exit(app.exec())
