from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_formEditar(object):
    def setupUi(self, formEditar):
        formEditar.setObjectName("formEditar")
        formEditar.resize(405, 323)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(formEditar)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=formEditar)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.txtEEmpleado = QtWidgets.QLineEdit(parent=formEditar)
        self.txtEEmpleado.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.UpArrowCursor))
        self.txtEEmpleado.setObjectName("txtEEmpleado")
        self.horizontalLayout.addWidget(self.txtEEmpleado)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=formEditar)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.txtENomComp = QtWidgets.QLineEdit(parent=formEditar)
        self.txtENomComp.setObjectName("txtENomComp")
        self.horizontalLayout_2.addWidget(self.txtENomComp)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(parent=formEditar)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.txtENumCentro = QtWidgets.QLineEdit(parent=formEditar)
        self.txtENumCentro.setObjectName("txtENumCentro")
        self.horizontalLayout_3.addWidget(self.txtENumCentro)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(parent=formEditar)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.txtEFecha = QtWidgets.QLineEdit(parent=formEditar)
        self.txtEFecha.setObjectName("txtEFecha")
        self.horizontalLayout_4.addWidget(self.txtEFecha)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(parent=formEditar)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.txtEPuesto = QtWidgets.QLineEdit(parent=formEditar)
        self.txtEPuesto.setObjectName("txtEPuesto")
        self.horizontalLayout_5.addWidget(self.txtEPuesto)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(parent=formEditar)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.txtESalario = QtWidgets.QLineEdit(parent=formEditar)
        self.txtESalario.setObjectName("txtESalario")
        self.horizontalLayout_6.addWidget(self.txtESalario)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(parent=formEditar)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.txtEGerente = QtWidgets.QLineEdit(parent=formEditar)
        self.txtEGerente.setObjectName("txtEGerente")
        self.horizontalLayout_7.addWidget(self.txtEGerente)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.brnEEditar = QtWidgets.QPushButton(parent=formEditar)
        self.brnEEditar.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.brnEEditar.setFont(font)
        self.brnEEditar.setObjectName("brnEEditar")
        self.verticalLayout_2.addWidget(self.brnEEditar)
        self.btnESalir = QtWidgets.QPushButton(parent=formEditar)
        self.btnESalir.setObjectName("btnESalir")
        self.verticalLayout_2.addWidget(self.btnESalir)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)

        self.retranslateUi(formEditar)
        QtCore.QMetaObject.connectSlotsByName(formEditar)

    def retranslateUi(self, formEditar):
        _translate = QtCore.QCoreApplication.translate
        formEditar.setWindowTitle(_translate("formEditar", "Editor"))
        self.label.setText(_translate("formEditar", "# Empleado"))
        self.label_2.setText(_translate("formEditar", "Nombre completo"))
        self.label_6.setText(_translate("formEditar", "# Centro"))
        self.label_5.setText(_translate("formEditar", "Fecha ingreso"))
        self.label_4.setText(_translate("formEditar", "Puesto Actual"))
        self.label_3.setText(_translate("formEditar", "Salario"))
        self.label_7.setText(_translate("formEditar", "Gerente"))
        self.brnEEditar.setText(_translate("formEditar", "Editar datos"))
        self.btnESalir.setText(_translate("formEditar", "Salir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formEditar = QtWidgets.QWidget()
    ui = Ui_formEditar()
    ui.setupUi(formEditar)
    formEditar.show()
    sys.exit(app.exec())
