from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_formBuscador(object):
    def setupUi(self, formBuscador):
        formBuscador.setObjectName("formBuscador")
        formBuscador.resize(670, 439)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(formBuscador)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(parent=formBuscador)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.txtEmpleado = QtWidgets.QLineEdit(parent=self.groupBox)
        self.txtEmpleado.setObjectName("txtEmpleado")
        self.horizontalLayout.addWidget(self.txtEmpleado)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.txtCentro = QtWidgets.QLineEdit(parent=self.groupBox)
        self.txtCentro.setObjectName("txtCentro")
        self.horizontalLayout_2.addWidget(self.txtCentro)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.txtGerente = QtWidgets.QLineEdit(parent=self.groupBox)
        self.txtGerente.setObjectName("txtGerente")
        self.horizontalLayout_3.addWidget(self.txtGerente)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnBuscar = QtWidgets.QPushButton(parent=formBuscador)
        self.btnBuscar.setObjectName("btnBuscar")
        self.horizontalLayout_5.addWidget(self.btnBuscar)
        self.btnEditar = QtWidgets.QPushButton(parent=formBuscador)
        self.btnEditar.setObjectName("btnEditar")
        self.horizontalLayout_5.addWidget(self.btnEditar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.gridBuscar = QtWidgets.QTableWidget(parent=formBuscador)
        self.gridBuscar.setObjectName("gridBuscar")
        self.gridBuscar.setColumnCount(0)
        self.gridBuscar.setRowCount(0)
        self.verticalLayout_2.addWidget(self.gridBuscar)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnEliminar = QtWidgets.QPushButton(parent=formBuscador)
        self.btnEliminar.setObjectName("btnEliminar")
        self.horizontalLayout_4.addWidget(self.btnEliminar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(formBuscador)
        QtCore.QMetaObject.connectSlotsByName(formBuscador)

    def retranslateUi(self, formBuscador):
        _translate = QtCore.QCoreApplication.translate
        formBuscador.setWindowTitle(_translate("formBuscador", "Buscador"))
        self.groupBox.setTitle(_translate("formBuscador", "Buscador"))
        self.label.setText(_translate("formBuscador", "# Empleado"))
        self.label_2.setText(_translate("formBuscador", "# Centro"))
        self.label_3.setText(_translate("formBuscador", "Gerente"))
        self.btnBuscar.setText(_translate("formBuscador", "Buscar"))
        self.btnEditar.setText(_translate("formBuscador", "Editar"))
        self.btnEliminar.setText(_translate("formBuscador", "Eliminar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formBuscador = QtWidgets.QWidget()
    ui = Ui_formBuscador()
    ui.setupUi(formBuscador)
    formBuscador.show()
    sys.exit(app.exec())
